name: Testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Prepare PATH
        run: |
          echo "::add-path::/home/runner/.local/bin"
      - name: Download Conan
        run: |
          pwd
          pip3 install wheel setuptools
          pip3 install conan
          conan --version
          ls
      - name: Build with CMake
        uses: ashutoshvarma/action-cmake-build@v1
        with:
          configure-options: -DBUILD_TESTING=1
          run-test: true
          ctest-options: --extra-verbose
